### ISSUE TITLE
作者你的测试出来的图是彩色的吗

### ISSUE THREAD

**Issue by zhangqifei1998** [viyiviyi/sd-encrypt-image#1]
我生成的图片为啥都是黑白的，而且用密码解密之后都是马赛克

**Comment by viyiviyi** [comment]
只有png格式在加密时不损失质量。我在readme文件里面写了。这个也能解决，就是加密的时候强制使用png格式保存图片，但是这样的后果是导致图片的实际格式和文件格式不一致，所有没有改。你可以用png格式保存图片来解决这个问题。解密出来是马赛克这个，如果密码正确是不应该的，除非图片的大小和加密时不一样了。
这个加密的原理只是打乱像素位置，加密后依然是一张图，会被压缩算法影响，也会被图片的大小影响。
