### ISSUE TITLE
新版插件无法直接在webui界面显示解密后的图片

### ISSUE THREAD

**Issue by BBrother-GFC** [viyiviyi/sd-encrypt-image#10]
![Clip_2024-03-17_10-46-18](https://github.com/viyiviyi/sd-encrypt-image/assets/51117375/7a33633c-79c2-410a-995b-b2f9c0746055)
![Clip_2024-03-17_10-46-59](https://github.com/viyiviyi/sd-encrypt-image/assets/51117375/a6af4ca6-2c90-4c04-8014-9cbd09b3b27a)

**Comment by DEX-1101** [comment]
您需要将 `--api` 添加到您的参数中，
