### ISSUE TITLE
在开启ADetailer时，生成的提示词有误

### ISSUE THREAD

**Issue by ronghuaxueleng** [viyiviyi/sd-encrypt-image#13]
如题：
在开启ADetailer时，生成的提示词有误
ADetailer配置如下：
![image](https://github.com/viyiviyi/sd-encrypt-image/assets/9460517/a5ba7a7e-a5ba-4c4e-8d67-a49a677022d8)
当未开启加密时图片的提示词如下：
![image](https://github.com/viyiviyi/sd-encrypt-image/assets/9460517/4caf4cfe-ebe7-45d5-909e-7019fb67a4da)
当开启加密时图片提示词如下：
![image](https://github.com/viyiviyi/sd-encrypt-image/assets/9460517/87fa2cf8-5073-4620-b6d9-88170f60b225)
可以看到正确的提示词被ADetailer中的提示词覆盖了

**Comment by viyiviyi** [comment]
> 如题： 在开启ADetailer时，生成的提示词有误 ADetailer配置如下： ![image](https://private-user-images.githubusercontent.com/9460517/342052914-a5ba7a7e-a5ba-4c4e-8d67-a49a677022d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjMyMjYsIm5iZiI6MTcxOTc2MjkyNiwicGF0aCI6Ii85NDYwNTE3LzM0MjA1MjkxNC1hNWJhN2E3ZS1hNWJhLTRjNGUtOGQ2Ny1hNDlhNjc3MDIyZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMTU1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWI4MDAxZDhkZTgwOTE3NmJjZmE0ZTU5NzQxMmU0NWEwMzg2NTYzODFkNTc3MTRjNzU2YzM1Yjc1NTA1ZGYyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9VScOPjPf0LG1tULKXHOCNtSE9x6ceBt0aU7tn39Y1U) 当未开启加密时图片的提示词如下： ![image](https://private-user-images.githubusercontent.com/9460517/342052951-4caf4cfe-ebe7-45d5-909e-7019fb67a4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjMyMjYsIm5iZiI6MTcxOTc2MjkyNiwicGF0aCI6Ii85NDYwNTE3LzM0MjA1Mjk1MS00Y2FmNGNmZS1lYmU3LTQ1ZDUtOTA5ZS03MDE5ZmI2N2E0ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMTU1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI5NDJmOTdkMzNhYjZiZGQ4NDQwMGExZmYyM2VmMmUyZTRhNDU5M2I4MzEwNDk4ZDhhOTMyODBjZGMwNTliZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a-PIKWNIirTKYqcpU26496AltMc7iJA7d4aza_OuEzQ) 当开启加密时图片提示词如下： ![image](https://private-user-images.githubusercontent.com/9460517/342052975-87fa2cf8-5073-4620-b6d9-88170f60b225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjMyMjYsIm5iZiI6MTcxOTc2MjkyNiwicGF0aCI6Ii85NDYwNTE3LzM0MjA1Mjk3NS04N2ZhMmNmOC01MDczLTQ2MjAtYjZkOS04ODE3MGY2MGIyMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMTU1NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJkY2ZlNWVkY2M0ZjMwNzJiN2EzMTZmY2QwNjM3MzdkNDU3Y2RkMjMyZDc4ZjQzOWI3YmE5MzY5Zjc0M2EyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EL_JVue_VIMK03H3xJmGw3IbTRIC6f2jPn3Yk74y0J4) 可以看到正确的提示词被ADetailer中的提示词覆盖了

你的意思是 用加密插件的情况下生成图片的时候的提示词会变成ADetailer的提示词吗？我测试没有这个问题，而且从原理上来讲，也不会出现这个问题，因为加密插件工作的原理是修改了图片最后写入磁盘的过程，和读取图片的过程，对其他过程是没有影响的。你出现这个问题更新一下ADetailer插件或者检查一下控制台是不是有保持导致某个插件工作异常了。
