### ISSUE TITLE
將圖片送至其他頁面的功能無法使用

### ISSUE THREAD

**Issue by w-e-w** [viyiviyi/sd-encrypt-image#4]
當前版本 980a4a3d 

將圖片送至其他頁面的功能無法使用
![image](https://github.com/viyiviyi/sd-encrypt-image/assets/40751091/8115e484-205f-4ce9-a8ef-c504a0274626)

```shell
Traceback (most recent call last):
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 320, in postprocess
    raise ValueError("Cannot process this value as an Image")
ValueError: Cannot process this value as an Image
```

> 連續找到一堆問題我都有點抱歉了

**Comment by viyiviyi** [comment]
> 當前版本 [980a4a3](https://github.com/viyiviyi/sd-encrypt-image/commit/980a4a3d4c47dba2838cd884e7f9c5033fcfe5e0)
> 
> 將圖片送至其他頁面的功能無法使用 ![image](https://user-images.githubusercontent.com/40751091/277103196-8115e484-205f-4ce9-a8ef-c504a0274626.png)
> 
> ```shell
> Traceback (most recent call last):
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 320, in postprocess
>     raise ValueError("Cannot process this value as an Image")
> ValueError: Cannot process this value as an Image
> ```
> 
> > 連續找到一堆問題我都有點抱歉了

这个我在readme有说明，这个问题我没法解决。主要是找不到原因

**Comment by viyiviyi** [comment]
> 當前版本 [980a4a3](https://github.com/viyiviyi/sd-encrypt-image/commit/980a4a3d4c47dba2838cd884e7f9c5033fcfe5e0)
> 
> 將圖片送至其他頁面的功能無法使用 ![image](https://user-images.githubusercontent.com/40751091/277103196-8115e484-205f-4ce9-a8ef-c504a0274626.png)
> 
> ```shell
> Traceback (most recent call last):
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 320, in postprocess
>     raise ValueError("Cannot process this value as an Image")
> ValueError: Cannot process this value as an Image
> ```
> 
> > 連續找到一堆問題我都有點抱歉了

笑死，突然就修好了，解决今天这个重要bug的时候，意外的也修复了这个问题。

**Comment by w-e-w** [comment]
冏
