### ISSUE TITLE
Grid image preview not appear / 网格图像预览不出现

### ISSUE THREAD

**Issue by DEX-1101** [viyiviyi/sd-encrypt-image#6]
网格图像预览显示不正确，除网格图像外其他一切正常

![370236080_1407994386761377_1196030084947932574_n](https://github.com/viyiviyi/sd-encrypt-image/assets/71503763/a46036a9-a653-4004-af7b-b24236c6a9e7)

**Comment by viyiviyi** [comment]
已修复
