### ISSUE TITLE
using batch size above 4 throwing an error / 使用大于 4 的批量大小会引发错误

### ISSUE THREAD

**Issue by DEX-1101** [viyiviyi/sd-encrypt-image#7]
![Screenshot_2](https://github.com/viyiviyi/sd-encrypt-image/assets/71503763/d6ab7729-c60b-4f2e-80ef-6f11b23cb75d)

**Comment by viyiviyi** [comment]
这个错是因为设置里面把大图保存为jpg格式导致的错，因为这个插件将图片强制保存为png来保证不丢失质量，而sd在使用jpg的方式将生成参数写入图片时就报错了。
