### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Yui007** [viyiviyi/sd-encrypt-image#8]
hi thanks for such a great extension but can u tell me how to install it step by step i want to use this in kaggle because kaggle doesn't allow NSFW pictures so can u tell me step by step how i install it in kaggle as an sd-automatic extension and use it

**Comment by DEX-1101** [comment]
` !git clone https://github.com/viyiviyi/sd-encrypt-image /kaggle/working/Stable Diffusion/extensions/sd-encrypt-image`
then put `--encrypt-pass=your_password` into your args,
make sure the webui directory is match your kaggle notebook

**Comment by Yui007** [comment]
thank you so much <3
