### ISSUE TITLE
New Error : InvalidImageDataError

### ISSUE THREAD

**Issue by Yui007** [viyiviyi/sd-encrypt-image#9]
hi, how are you . I am back with another issue this time .I followed your every step but i am getting this error but the extension is working fine but i am getting this error after every picture i generate. it causes issues like taking double size because it is also creating the same img but ending with .tmp so double size
![githubb](https://github.com/viyiviyi/sd-encrypt-image/assets/129981733/6e8ff4b5-1952-411b-996f-2c97e9fbb86f)
![githubbb](https://github.com/viyiviyi/sd-encrypt-image/assets/129981733/53331a06-343e-44f2-99d0-8d40899f4aa2)

**Comment by Yui007** [comment]
I Fixed It by turning off the options. grid files ones

**Comment by viyiviyi** [comment]
当插件生效时，图片的实际格式将会是PNG，这可以解决压缩时的损失，但也会导致非PNG格式的图片可能出错。
When the plugin is in effect, the actual format of the image will be PNG, which can solve the loss of compression, but also cause non-PNG images may be wrong.
